# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1024, 600)
        MainWindow.setMinimumSize(QtCore.QSize(1024, 600))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("color: rgb(255, 170, 127);")
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(0, 0, 1024, 600))
        self.widget.setMinimumSize(QtCore.QSize(1024, 600))
        self.widget.setStyleSheet("background-color: #17AEAA;")
        self.widget.setObjectName("widget")
        self.frame_2 = QtWidgets.QFrame(self.widget)
        self.frame_2.setGeometry(QtCore.QRect(45, 30, 931, 531))
        self.frame_2.setStyleSheet("border: 1px  ;\n"
"border-radius: 40px; \n"
"background-color: #FFF6ED;\n"
"align-items: center;")
        self.frame_2.setObjectName("frame_2")
        self.widget_3 = QtWidgets.QWidget(self.frame_2)
        self.widget_3.setGeometry(QtCore.QRect(90, 310, 91, 51))
        self.widget_3.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"background-color: #17AEAA;\n"
"border-radius: 14px")
        self.widget_3.setObjectName("widget_3")
        self.label_7 = QtWidgets.QLabel(self.widget_3)
        self.label_7.setGeometry(QtCore.QRect(20, 15, 61, 21))
        self.label_7.setStyleSheet("font-size: 20px;\n"
"color:white;")
        self.label_7.setObjectName("label_7")
        self.widget_4 = QtWidgets.QWidget(self.frame_2)
        self.widget_4.setGeometry(QtCore.QRect(200, 310, 91, 51))
        self.widget_4.setStyleSheet("background-color: #17AEAA;\n"
"border-radius: 14px;")
        self.widget_4.setObjectName("widget_4")
        self.label_4 = QtWidgets.QLabel(self.frame_2)
        self.label_4.setGeometry(QtCore.QRect(40, 30, 81, 50))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("C:/Users/Desktop/Desktop/aa-120x120.webp"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.dateTimeEdit = QtWidgets.QDateTimeEdit(self.frame_2)
        self.dateTimeEdit.setGeometry(QtCore.QRect(720, 490, 171, 22))
        self.dateTimeEdit.setStyleSheet("color: rgb(0, 0, 0);\n"
"font-size: 13pt;")
        self.dateTimeEdit.setObjectName("dateTimeEdit")
        self.label_5 = QtWidgets.QLabel(self.frame_2)
        self.label_5.setGeometry(QtCore.QRect(80, 200, 401, 61))
        self.label_5.setStyleSheet("font-size:56px;\n"
"color:black;")
        self.label_5.setObjectName("label_5")
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setGeometry(QtCore.QRect(830, 40, 31, 31))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("images/settings.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.frame_2)
        self.label_3.setGeometry(QtCore.QRect(750, 40, 31, 31))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("images/user.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.label = QtWidgets.QLabel(self.frame_2)
        self.label.setGeometry(QtCore.QRect(790, 40, 31, 31))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("images/report.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_6 = QtWidgets.QLabel(self.frame_2)
        self.label_6.setGeometry(QtCore.QRect(590, 140, 251, 261))
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("images/laboratory-centrifuge-color-icon-isolated-illustration-vector-removebg-preview.png"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_7.setText(_translate("MainWindow", "Home"))
        self.label_5.setText(_translate("MainWindow", "Welcome Admin"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
